### ISSUE TITLE
Untrack file

### ISSUE THREAD

**Issue by AlexIliescu11** [mariacatalina1508/IT-School#1]
Please consider to untrack `.idea` package.

You can use the following commands:
`git rm --cached <file>` This command removes the specified file from Git's tracking, but it keeps the file in your working directory.
`git rm -r --cached <directory>` This recursively removes all files within the specified directory from Git's tracking, while leaving them in your working directory.

![image](https://github.com/mariacatalina1508/IT-School/assets/120710343/16115cd4-8524-4328-9f8c-ffe1fd8a868e)

**Comment by mariacatalina1508** [comment]
the issue is resolved!
